language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
install:
  - pip install -e .
  - pip install requests pytest-cov coveralls
before_script:
  - docker-compose -f tests/config/docker-compose.yml up -d
  - sleep 40
  - ./tests/config/bootstrap
script: py.test -v --cov=pygelf
after_script:
  - docker-compose -f tests/config/docker-compose.yml down
after_success:
  - coveralls